# Generated by Django 3.2.7 on 2021-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradesdata',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('dept', models.TextField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('prof', models.TextField(blank=True, null=True)),
                ('sect', models.IntegerField(blank=True, null=True)),
                ('sem', models.TextField(blank=True, null=True)),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('a', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('f', models.IntegerField(blank=True, null=True)),
                ('q', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gradesdata',
                'managed': False,
            },
        ),
    ]
